const sidebar = {
  "/1.base/1.html/": [
    "1.index",
    '1.element',
    '2.attrs',
    '3.events',
    '4.code',
  ],
  "/1.base/2.css/": [
    "1.index",
    "1.grammar",
    "2.select",
    "3.position",
    "4.layout",
    "5.style",
    '6.animation',
    '7.yong'
  ],
  "/1.base/3.javascript/": [
    "1.index",
    "1.grammar",
    "2.morphology",
    "3.context",
    "4.variableobj",
    "5.scope",
    "6.closure",
    "7.this",
    "8.async",
    "9.eventloop",
    "10.dom",
    "11.bom",
  ],
  "/2.advanced/1.h5/": [
    "1.index",
  ],
  "/7.read/book1/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book2/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book3/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book4/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book5/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
};
module.exports = sidebar;
